article/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$',views.article_list,name="list" ),
    url(r'^create/$',views.article_create,name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail"),
]

djangonautic/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from article import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^article/',include('article.urls')),
    url(r'^exam/',include('exam.urls')),
    url(r'^$',article_views.article_list, name="home"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exam/urls.py
from django.conf.urls import url
from . import views

app_name = 'exam'

urlpatterns = [
    url(r'^take$',views.exam,name="exam_start" ),

]

article/models.py
from django.db import models
from django.contrib.auth.models import User




class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='logo.png', blank=True)
    author = models.ForeignKey(User,default=None, on_delete=models.CASCADE)



    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

article/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb',]

article/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
     articles = Article.objects.all().order_by('date')
     return render(request,'articles/article_list.html',{'articles':articles})

def article_detail(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
      form = forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

exam/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required


def exam(request):
    return render(request, 'exam/exam.html')

article/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
  <div class="create-article">
    <form class="site-form" action="{% url 'articles:create' %}" method="post"
    enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Create">
    </form>
  </div>
  <script src="/static/slugify.js">
  </script>

{% endblock %}

article/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
     <div class="article-detail">
       <div class="article">
          <img src="{{ article.thumb.url }}"/>
          <h2>{{ article.title }}</h2>
          <p>{{ article.body }}</p>
          <p>{{ article.date }}</p>
       </div>
     </div>
  {% endblock %}

article/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
     <div class="articles">
       {% for article in articles %}
       <div class="article">
          <h2><a href="{%  url 'articles:detail' slug=article.slug %}">
            {{ article.title }}
          </a></h2>
          <p>{{ article.snippet }}</p>
          <p>{{ article.date }}</p>
          <p class="author">added by {{article.author.username}} </p>
       </div>
       {% endfor %}
     </div>
  {% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>fiercecom Incorporated</title>
    <link rel="icon" href="{% static 'fierce.png' %}" type="image/icon type">
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>

  <body>
    <div class="wrapper" >
      <h1>
          <img src="{% static 'j.png' %}" class="center"  style="width:100%;">
          <nav>
                <li>
                  <a class="home" href="{% url 'exam:exam_start'%}"
                  style="position: relative;
                  bottom: 25px;
                  right: 5px;
                  border: 2px solid green;
                  padding: 15px;
                  border-radius: 10px;
                  color: black;
                  font-size: 40px">CLICK HERE TO START</a>
                </li>
          </nav>
      </h1>
      {% block content %}

      {% endblock %}

    </div>
  </body>
</html>